language: ruby

sudo: false

rvm:
  - 2.0.0
  - 2.1
  - 2.2

install:
  - "travis_retry bundle config build.nokogiri --use-system-libraries"
  - "travis_retry bundle install --retry 3"

script: bundle exec rake

git:
  depth: 10
